server:
  port: 8088

jwt:
  secret:
    key: in_a_hole_in_the_ground_there_lived_a_hobbit # hobbit first line
  access:
    expiration: 20
    header: Authorization

  refresh:
    expiration: 30
    header: AuthorizationRefresh

spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 778075682082-6tkmcmtkh60nfo1dajbe6vvo97mhckob.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
